# Generated by Django 5.2.4 on 2025-07-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNGroupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_2fa', models.BooleanField(default=True, help_text='이 그룹은 2FA를 필수로 요구합니다')),
                ('allow_without_2fa', models.BooleanField(default=False, help_text='2FA 없이도 VPN 접근 허용')),
                ('grace_period_hours', models.IntegerField(default=24, help_text='2FA 설정 유예 기간 (시간)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_policy', to='auth.group')),
            ],
            options={
                'verbose_name': 'VPN Group Policy',
                'verbose_name_plural': 'VPN Group Policies',
            },
        ),
    ]
