# Generated by Django 5.2.4 on 2025-07-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_vpngrouppolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpngrouppolicy',
            name='allowed_end_time',
            field=models.TimeField(blank=True, help_text='접속 허용 종료 시간 (예: 18:00)', null=True),
        ),
        migrations.AddField(
            model_name='vpngrouppolicy',
            name='allowed_start_time',
            field=models.TimeField(blank=True, help_text='접속 허용 시작 시간 (예: 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='vpngrouppolicy',
            name='allowed_weekdays',
            field=models.CharField(default='1,2,3,4,5', help_text='접속 허용 요일 (월=1, 화=2, 수=3, 목=4, 금=5, 토=6, 일=7)', max_length=20),
        ),
        migrations.AddField(
            model_name='vpngrouppolicy',
            name='enable_time_restriction',
            field=models.BooleanField(default=False, help_text='시간 제한 활성화'),
        ),
        migrations.AddField(
            model_name='vpngrouppolicy',
            name='timezone',
            field=models.CharField(default='Asia/Seoul', help_text='시간대 설정', max_length=50),
        ),
    ]
